export interface MashStep {
  name: string,
  version: number,
  type: 'Infusion' | 'Temperature' | 'Decoction',
  infuseAmount: number,
  infuseTemp: number,
  stepTemp: number,
  stepTime: number,
  rampTime: number,
  endTemp: number,
  description: string,
  waterToGrainRatio: number,
  decoctAmount: number,
  ownerId: number,
  id: number,
  order: number,
  calcInfuseTemp: number,
  calcInfuseAmount: number,
  calcDecoctAmount: number
}
